# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FractalxCli < Formula
  desc "FractalX CLI — generate a Spring Boot monolith ready for decomposition"
  homepage "https://github.com/fractalx-org/fractalx-cli"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fractalx-org/fractalx-cli/releases/download/v0.1.0/fractalx-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "f8d95cfe1ca9a542869fb8c33928fd1479a20d58eb9e06d3d128055e8043398e"

      define_method(:install) do
        bin.install "fractalx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fractalx-org/fractalx-cli/releases/download/v0.1.0/fractalx-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "367d19fb17bd7e426efcc1a826f2f14941c6d678576acdb2386bdf9e45c200cf"

      define_method(:install) do
        bin.install "fractalx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fractalx-org/fractalx-cli/releases/download/v0.1.0/fractalx-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "e32f5a69247c54149edb9fe2327e496249dc92654751ece15524d1120e057f11"
      define_method(:install) do
        bin.install "fractalx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fractalx-org/fractalx-cli/releases/download/v0.1.0/fractalx-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "010fcc403d360749af72ce99c9f474d3796de64ba8c30c114c05664d06778811"
      define_method(:install) do
        bin.install "fractalx"
      end
    end
  end

  test do
    system "#{bin}/fractalx", "--help"
  end
end
