# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FractalxCli < Formula
  desc "FractalX CLI — generate a Spring Boot monolith ready for decomposition"
  homepage "https://github.com/fractalx-org/fractalx-cli"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fractalx-org/fractalx-cli/releases/download/v0.1.1/fractalx-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "c19386308113b533734603fed0a50d0bee8b08e8b9887c81aa521d1703046214"

      define_method(:install) do
        bin.install "fractalx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fractalx-org/fractalx-cli/releases/download/v0.1.1/fractalx-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "45a4ab69989f37554c6ed4e2a2babe7d31c7654d03acf137dd9695ed73ea4824"

      define_method(:install) do
        bin.install "fractalx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fractalx-org/fractalx-cli/releases/download/v0.1.1/fractalx-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "d051ad005c98eea258c1c5d25112293faafbdfebfbaae2a581638e70dadee48e"
      define_method(:install) do
        bin.install "fractalx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fractalx-org/fractalx-cli/releases/download/v0.1.1/fractalx-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "da7dcc6c6b1d8780072491c3c3003d7de67a87fb6564a48a698cea34f7dce491"
      define_method(:install) do
        bin.install "fractalx"
      end
    end
  end

  test do
    system "#{bin}/fractalx", "--help"
  end
end
